version: '3.9'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: capstone-api-gateway
    ports:
      - "8085:8085"
    depends_on:
      - account-service
      - client-service
      - keycloak
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYCLOAK_URL=http://keycloak:8080
      - ACCOUNT_SERVICE_URL=http://account-service:8082
      - CLIENT_SERVICE_URL=http://client-service:8081
    networks:
      - capstone-net

  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    container_name: capstone-account-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYCLOAK_URL=http://keycloak:8080
    networks:
      - capstone-net

  client-service:
    build:
      context: ./client-service
      dockerfile: Dockerfile
    container_name: capstone-client-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYCLOAK_URL=http://keycloak:8080
    networks:
      - capstone-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
      - --hostname=keycloak
      - --hostname-port=8080
      - --hostname-strict=false
      - --hostname-strict-https=false
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
    ports:
      - "8084:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    networks:
      - capstone-net


networks:
  capstone-net:
    driver: bridge
